apiVersion: v1
kind: Namespace
metadata:
  name: gpu-telemetry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcgm-exporter
  namespace: gpu-telemetry
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: gpu-telemetry
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  template:
    metadata:
      labels:
        app: dcgm-exporter
    spec:
      serviceAccountName: dcgm-exporter
      containers:
        - name: exporter
          image: nvcr.io/nvidia/k8s/dcgm-exporter:3.1.8-2.6.7-ubuntu20.04
          ports:
            - containerPort: 9400
---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: gpu-telemetry
spec:
  selector:
    app: dcgm-exporter
  ports:
    - port: 9400
      targetPort: 9400
