# NVIDIA DCGM Exporter exposes GPU metrics in Prometheus format.
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-metrics
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: gpu-metrics
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  template:
    metadata:
      labels:
        app: dcgm-exporter
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: dcgm-exporter
          image: nvcr.io/nvidia/k8s/dcgm-exporter:3.2.4-2.6.12-ubuntu22.04 # TODO: bump as needed
          ports:
            - containerPort: 9400
              name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: gpu-metrics
spec:
  selector:
    app: dcgm-exporter
  ports:
    - port: 9400
      targetPort: metrics
# Optional ServiceMonitor for Prometheus Operator
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: dcgm-exporter
#   namespace: gpu-metrics
# spec:
#   selector:
#     matchLabels:
#       app: dcgm-exporter
#   namespaceSelector:
#     matchNames:
#       - gpu-metrics
#   endpoints:
#     - port: metrics
