apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
        containers:
          - name: metrics-server
            image: k8s.gcr.io/metrics-server/metrics-server:v0.6.4
            # No insecure flags by default; add --kubelet-insecure-tls only in dev overlays
            args: []
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  selector:
    k8s-app: metrics-server
  ports:
    - port: 443
      targetPort: 4443
