apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - name: echo
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 20m
              memory: 32Mi
