name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install pre-commit yamllint
          npm install -g markdownlint-cli
      - run: pre-commit run --all-files

  kustomize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay: [dev, prod]
    steps:
      - uses: actions/checkout@v4
      - run: |
          if command -v kubectl >/dev/null 2>&1; then
            kubectl kustomize ./kustomize/overlays/${{ matrix.overlay }} >/dev/null
          else
            sudo apt-get update && sudo apt-get install -y kustomize
            kustomize build ./kustomize/overlays/${{ matrix.overlay }} >/dev/null
          fi
