name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install kubectl
        run: |
          curl -L -o kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo install -o root -g root -m 0755 kubeconform /usr/local/bin/kubeconform
      - name: Run pre-commit
        run: pre-commit run --files $(git ls-files '*.yaml' '*.yml' '*.md' 'Makefile')
      - name: kubeconform
        run: |
          kubectl kustomize kustomize/overlays/prod | kubeconform -strict -
